# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
kramdown:
   input: GFM
   highlighter: rouge
   syntax_highlighter_opts:
       block:
           line_numbers: true



defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: El Javiador

permalink: "/:title.html"
description: Blog personal sobre la plataforma Java
author:
  name: Franky Villadiego
  github:
  twitter: villadiegofj
  bio: Volando hacia el desarrollo productivo!
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:  https://eljaviador.com

future: false

plugins:
  - jekyll-gist
  - jekyll-paginate

